### ISSUE TITLE
where Hg38_primary_targets.bed?

### ISSUE THREAD

**Issue by wenyuhaokikika** [mdelcorvo/TOSCA#5]
when i run 
```sh
$ snakemake --use-conda --cores all --configfile config/config.yaml --wrapper-prefix file:///data/wenyuhao/tmp/runWGS/tmp/TOSCA/
Building DAG of jobs...
MissingInputException in line 1 of /data/wenyuhao/tmp/runWGS/tmp/TOSCA/rules/calling.smk:
Missing input files for rule callable:
/scratch/Hg38_primary_targets.bed
```
i dont know where ```/scratch/Hg38_primary_targets.bed```and ```/scratch/Hg38_capture_targets.bed```,
please give me a url to download

**Comment by wenyuhaokikika** [comment]
I downloaded him from https://sequencing.roche.com/global/en/products/group/kapa-hyperexome.html 

but I don't know if it is correct

**Comment by mdelcorvo** [comment]
Hi, thank you for trying TOSCA. About primary target, there is not a specific bed file, you should provide in the config file the one you used during your experiment. 

So this means to tell TOSCA which regions have been covered when you sequenced the samples that you want to analyze (could be for example a single gene or the entire exome).
If you provide a wrong file, you could end up with regions with NO coverage that will be systematically discarded from the analysis.

**Comment by wenyuhaokikika** [comment]
Thank you for such a quick reply~~~

I think TOSCA is very nice project!

Sorry, according to what you said, I think I may not need this step, I get data from GEO, and I need complete somatic mutations, so I commented these two lines
```config
#baits: resources/design-files-hg38-kapa-hyperexome-probes/HyperExome_hg
filtering:
## Provide BED file of your targeted capture
  #restrict-regions: resources/design-files-hg38-kapa-hyperexome-probes/
## Minimum read depth to call a variant (100-250x suggested)   
  min_depth: 250 
## Minimum variant allele frequency (5% suggested)  
  vaf: 0.05 
```
it raise Exception
```
$ snakemake --use-conda --cores all --configfile config/config.yaml --wrapper-prefix file:///data/wenyuhao/tmp/runWGS/tmp/TOSCA/
KeyError in line 5 of /data/wenyuhao/tmp/runWGS/tmp/TOSCA/rules/calling.smk:
'restrict-regions'
  File "/data/wenyuhao/tmp/runWGS/tmp/TOSCA/Snakefile", line 31, in <module>
  File "/data/wenyuhao/tmp/runWGS/tmp/TOSCA/rules/calling.smk", line 5, in <module>
```
What should I do？

and data from https://www.ncbi.nlm.nih.gov/bioproject/?term=PRJNA565658

it do not provide bed file.

**Comment by mdelcorvo** [comment]
Hi, you can't comment `restrict-regions` parameter, it is mandatory in order to know in which regions to call variants.

I briefly checked the GEO link you sent to me, and it seems that this project is about rna-seq and whole-genome sequencing. Since TOSCA has been developed for whole-exome and target panel only, they do not seem to be the most appropriate datasets to analyze with this tool. Also because a high coverage data is usually needed to discriminate between somatic and germline variants and whole genome sequencing tends to be low-level.

Having said that, if you still want to analyze these data with TOSCA, I suggest to provide as `restrict-regions` a whole-exome target file. You could start with the most common Agilent sureselect file. 

If you don't know how to download it, here's how: go to https://earray.chem.agilent.com/suredesign/index.htm (you will need to create an account), then click "find designs", then click "SureSelectDNA", then click "agilent catalog", then you get to a list of a bunch of sureselect kits with download links including .bed files. You can choose the one named 'SureSelect Human All Exon V7'

I also suggest to set `min_depth` parameter to 100

**Comment by wenyuhaokikika** [comment]
thank you very much~

I download bed file from https://earray.chem.agilent.com/,  it provide files

![image](https://user-images.githubusercontent.com/40107519/228220157-ca57d25c-0263-4f19-a8b7-14a42d03ebc1.png)

I use ```S31285117_AllTracks.bed```
I modified the configuration file as follows
```
#baits: resources/design-files-hg38-kapa-hyperexome-probes/HyperExome_hg38_capture_targets.bed
filtering:
## Provide BED file of your targeted capture
  restrict-regions: resources/S31285117_hs_hg38/S31285117_AllTracks.bed
## Minimum read depth to call a variant (100-250x suggested)   
  min_depth: 100
## Minimum variant allele frequency (5% suggested)  
  vaf: 0.05
```
another problem you said 'Since TOSCA has been developed for whole-exome and target panel only, they do not seem to be the most appropriate datasets to analyze with this tool.'

My understanding is that TOSCA is designed for Whole Exome Sequencing (WES), which has a higher sequencing depth compared to Whole Genome Sequencing (WGS). Therefore, I will lower the min_depth to 100.

I am confused. I would like to know whether it is feasible to use TOSCA to detect somatic mutations for WGS data, and whether there are any downsides 

Thank you for your reply!
