### ISSUE TITLE
database_url  GRCh37 ESP

### ISSUE THREAD

**Issue by feihongloveworld** [mdelcorvo/TOSCA#7]
why are GRCh38?
![image](https://github.com/mdelcorvo/TOSCA/assets/30719145/af98216a-959e-4b5a-95f9-7fff02235195)

**Comment by mdelcorvo** [comment]
Hi, thank you for trying TOSCA. 

About the ESP database, the file listed in the config file for GRCh37 build (`ESP6500SI-V2-SSA137.GRCh38-liftover.snps_indels.vcf.tar.gz`) is correct, since it provides coordinates for both hg38 and hg19 reference genome (thats why its called _GRCh38 liftover_).

So depending on the genome version you choose in the config file, TOSCA will then select the proper coordinates accordingly
